package com.example.croceverdeplus

import com.google.firebase.Timestamp

class Tabella118h24 {
    var tipo_settimana: Boolean = true
    var data_lunedi: Timestamp? = null
    var data_martedi: Timestamp? = null
    var data_mercoledi: Timestamp? = null
    var data_giovedi: Timestamp? = null
    var data_venerdi: Timestamp? = null
    var data_sabato: Timestamp? = null
    var data_domenica: Timestamp? = null

    var turno_118_lun_mat_1 = ""
    var turno_118_lun_mat_2 = ""
    var turno_118_lun_mat_3 = ""
    var turno_118_lun_pom_1 = ""
    var turno_118_lun_pom_2 = ""
    var turno_118_lun_pom_3 = ""
    var turno_118_lun_ser_1 = ""
    var turno_118_lun_ser_2 = ""
    var turno_118_lun_ser_3 = ""

    var turno_118_mar_mat_1 = ""
    var turno_118_mar_mat_2 = ""
    var turno_118_mar_mat_3 = ""
    var turno_118_mar_pom_1 = ""
    var turno_118_mar_pom_2 = ""
    var turno_118_mar_pom_3 = ""
    var turno_118_mar_ser_1 = ""
    var turno_118_mar_ser_2 = ""
    var turno_118_mar_ser_3 = ""

    var turno_118_mer_mat_1 = ""
    var turno_118_mer_mat_2 = ""
    var turno_118_mer_mat_3 = ""
    var turno_118_mer_pom_1 = ""
    var turno_118_mer_pom_2 = ""
    var turno_118_mer_pom_3 = ""
    var turno_118_mer_ser_1 = ""
    var turno_118_mer_ser_2 = ""
    var turno_118_mer_ser_3 = ""

    var turno_118_gio_mat_1 = ""
    var turno_118_gio_mat_2 = ""
    var turno_118_gio_mat_3 = ""
    var turno_118_gio_pom_1 = ""
    var turno_118_gio_pom_2 = ""
    var turno_118_gio_pom_3 = ""
    var turno_118_gio_ser_1 = ""
    var turno_118_gio_ser_2 = ""
    var turno_118_gio_ser_3 = ""

    var turno_118_ven_mat_1 = ""
    var turno_118_ven_mat_2 = ""
    var turno_118_ven_mat_3 = ""
    var turno_118_ven_pom_1 = ""
    var turno_118_ven_pom_2 = ""
    var turno_118_ven_pom_3 = ""
    var turno_118_ven_ser_1 = ""
    var turno_118_ven_ser_2 = ""
    var turno_118_ven_ser_3 = ""

    var turno_118_sab_mat_1 = ""
    var turno_118_sab_mat_2 = ""
    var turno_118_sab_mat_3 = ""
    var turno_118_sab_pom_1 = ""
    var turno_118_sab_pom_2 = ""
    var turno_118_sab_pom_3 = ""
    var turno_118_sab_ser_1 = ""
    var turno_118_sab_ser_2 = ""
    var turno_118_sab_ser_3 = ""

    var turno_118_dom_mat_1 = ""
    var turno_118_dom_mat_2 = ""
    var turno_118_dom_mat_3 = ""
    var turno_118_dom_pom_1 = ""
    var turno_118_dom_pom_2 = ""
    var turno_118_dom_pom_3 = ""
    var turno_118_dom_ser_1 = ""
    var turno_118_dom_ser_2 = ""
    var turno_118_dom_ser_3 = ""

    var turno_h24_lun_mat_1 = ""
    var turno_h24_lun_mat_2 = ""
    var turno_h24_lun_mat_3 = ""
    var turno_h24_lun_pom_1 = ""
    var turno_h24_lun_pom_2 = ""
    var turno_h24_lun_pom_3 = ""
    var turno_h24_lun_ser_1 = ""
    var turno_h24_lun_ser_2 = ""
    var turno_h24_lun_ser_3 = ""

    var turno_h24_mar_mat_1 = ""
    var turno_h24_mar_mat_2 = ""
    var turno_h24_mar_mat_3 = ""
    var turno_h24_mar_pom_1 = ""
    var turno_h24_mar_pom_2 = ""
    var turno_h24_mar_pom_3 = ""
    var turno_h24_mar_ser_1 = ""
    var turno_h24_mar_ser_2 = ""
    var turno_h24_mar_ser_3 = ""

    var turno_h24_mer_mat_1 = ""
    var turno_h24_mer_mat_2 = ""
    var turno_h24_mer_mat_3 = ""
    var turno_h24_mer_pom_1 = ""
    var turno_h24_mer_pom_2 = ""
    var turno_h24_mer_pom_3 = ""
    var turno_h24_mer_ser_1 = ""
    var turno_h24_mer_ser_2 = ""
    var turno_h24_mer_ser_3 = ""

    var turno_h24_gio_mat_1 = ""
    var turno_h24_gio_mat_2 = ""
    var turno_h24_gio_mat_3 = ""
    var turno_h24_gio_pom_1 = ""
    var turno_h24_gio_pom_2 = ""
    var turno_h24_gio_pom_3 = ""
    var turno_h24_gio_ser_1 = ""
    var turno_h24_gio_ser_2 = ""
    var turno_h24_gio_ser_3 = ""

    var turno_h24_ven_mat_1 = ""
    var turno_h24_ven_mat_2 = ""
    var turno_h24_ven_mat_3 = ""
    var turno_h24_ven_pom_1 = ""
    var turno_h24_ven_pom_2 = ""
    var turno_h24_ven_pom_3 = ""
    var turno_h24_ven_ser_1 = ""
    var turno_h24_ven_ser_2 = ""
    var turno_h24_ven_ser_3 = ""

    var turno_h24_sab_mat_1 = ""
    var turno_h24_sab_mat_2 = ""
    var turno_h24_sab_mat_3 = ""
    var turno_h24_sab_pom_1 = ""
    var turno_h24_sab_pom_2 = ""
    var turno_h24_sab_pom_3 = ""
    var turno_h24_sab_ser_1 = ""
    var turno_h24_sab_ser_2 = ""
    var turno_h24_sab_ser_3 = ""

    var turno_h24_dom_mat_1 = ""
    var turno_h24_dom_mat_2 = ""
    var turno_h24_dom_mat_3 = ""
    var turno_h24_dom_pom_1 = ""
    var turno_h24_dom_pom_2 = ""
    var turno_h24_dom_pom_3 = ""
    var turno_h24_dom_ser_1 = ""
    var turno_h24_dom_ser_2 = ""
    var turno_h24_dom_ser_3 = ""
}